# Build pipeline for publishing

trigger:
  batch: true
  branches:
    include:
      - nuget-dev

pr: none

variables:
  - group: 'NPM and Github Secrets'

jobs:
  - job: NuGetPublish
    displayName: NuGet Publish
    pool:
      vmImage: 'macos-10.15'
      demands: ['xcode', 'sh', 'npm']
    timeoutInMinutes: 90 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them

    steps:
      - checkout: self
        persistCredentials: true

      - script: |
          git config user.name "UI-Fabric-RN-Bot"
          git config user.email "uifrnbot@microsoft.com"
          git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/ui-fabric-react-native.git
        displayName: Git Authentication

      - template: templates/yarn-install.yml

      # Clean Derived Data
      - script: |
          rm -rf $(Build.Repository.LocalPath)/DerivedData
        displayName: 'Clean DerivedData'

      - script: |
          sudo gem install cocoapods
        displayName: 'Install CocoaPods Environment'

      - script: |
          pod repo add rdeassis https://github.com/rdeassis/cocoapods-repo.git
        displayName: 'Add Private Pod Source'

      - script: |
          yarn bundle ios
        workingDirectory: $(Build.Repository.LocalPath)/apps/ios
        displayName: 'yarn bundle iOS'

      - script: |
          yarn bundle macos
        workingDirectory: $(Build.Repository.LocalPath)/apps/macos
        displayName: 'yarn bundle macOS'

      # Select proper Xcode version
      - template: templates/apple-xcode-select.yml

      - template: templates/apple-xcode-build-static-libs.yml

      - template: templates/nuget-publish.yml
